backend:
  name: github
  repo: curokami/blog-project-
  branch: main
  site_domain: blog-project-398.pages.dev
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "ブログ記事"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "pubDate", widget: "datetime" }
      - { label: "著者", name: "author", widget: "string" }
      - { label: "概要", name: "description", widget: "text" }
      - { label: "画像", name: "image", widget: "image" }
      - { label: "タグ", name: "tags", widget: "list", allow_add: true }
      - { label: "本文", name: "body", widget: "markdown" }